info:
  contact: {}
  description: 这里是描述
  title: 项目名称
  version: "1.0"
paths:
  /download:
    post:
      description: 描述信息
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 下载文件
  /hello:
    get:
      description: 描述信息
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 返回hello gin
  /test:
    get:
      description: 描述信息
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 测试用token鉴权
  /token:
    get:
      description: 描述信息
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 获取token
  /upload:
    post:
      description: 描述信息
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 上传文件
swagger: "2.0"
